const swaggerUi = require('swagger-ui-express');
const swaggerDoc = require('swagger-jsdoc');

const option = {
    swaggerDefinition: {
        info: {
            title: 'Test API',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc'
        }
    },
    apis: ['./routes/users.js']
};

const specs = swaggerDoc(option);

module.exports = (app) => {
    app.use('/swagger', swaggerUi.serve, swaggerUi.setup(specs));
};